services:
  - type: web
    name: test-orders-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false 