services:
  - type: web
    name: test-orders-backend
    env: node
    buildCommand: npm run install-all
    startCommand: npm start
    envVars:
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false 